on:
  push:
    branches:
    - main
    tags:
    - '!*'
  pull_request:
    branches:
    - main

name: main
jobs:
  update_github_pages:
    name: Update github pages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run lint
      run: |
        set -e
        npm ci
        npm run lint

    - name: Run build
      run: npm run build

    - name: Publish ghpages branch
      run: |
        set -e
        mv dist ..
        git checkout --orphan ghpages
        git reset --hard
        cp -R ../dist/* .
        git add .
        git commit -m "Updated GitHub pages"