on:
  push:
    branches:
    - main
    tags:
    - '!*'
  pull_request:
    branches:
    - main

name: main
jobs:
  update_github_pages:
    name: Update github pages
    container:
      image: ubuntu:bionic
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        set -e
        apt-get update -y
        apt-get install -y git
        npm ci

    - name: Run lint
      run: npm run lint

    - name: Run build
      run: npm run build

    - name: Publish ghpages branch
      run: |
        set -e
        mv dist /dist
        git checkout --orphan ghpages
        git reset --hard
        cp -R /dist/* .
        git add .